module.exports = {
    FB_PAGE_TOKEN: 'EAAGRfDZAL6DUBACW4tVGxCgOOfhbwDVjNNLyrIAedB83UB5D6oZB3FMow82sN4os9iW18gdYPBhggZCpefKAZAg5naqwM4TvOl5fnGVBxhcZC5H8CJvgv6GO4VI7nJAQOvfEws8JLuglAsfPVrW4abl0jnDaMtRt4u7krNOzIHAZDZD',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
};
