module.exports = {
    FB_PAGE_TOKEN: 'EAAdc6gZAk2b8BAEPxzT5PgQGCeZCe2OaZCLlhZArqMeSZCIYYZBDHRMXwb7tNiZAr4wi6F2pPEntC0ruX2nNdqDibJd3eTmmZB0cAi7XTDUzDRJ6ZCZBZCM2rdbCDMXKm7IU7gJLN44WlnwZBSt3UOTDuikyQI7eI6jBEjaWGqd0jcCWIwZDZD',
    FB_VERIFY_TOKEN: '',
    API_AI_CLIENT_ACCESS_TOKEN: '',
    FB_APP_SECRET: '',
    SERVER_URL: "",
};
